### PR TITLE
Updates on the use cases

### PR DESCRIPTION
**Pull request by mahyar-osn**
- Use case 3 added,
- Use case 4 updated to match the new portal UI,
- Use case 1 updated.

### CODE REVIEW

**Comment by agarny** [comment]
@mahyar-osn, we thought you were working on the mouse heart and not also on use case 4, hence I created a PR for it 30 minutes ago...

**Comment by agarny** [comment]
Otherwise, @mahyar-osn, it would be good to have one PR per use case. It will make it easier to review.

**Comment by mahyar-osn** [comment]
Oh, sorry @agarny about this. I presumed you guys were asleep now. OK so should I revert the use case 4 changes?

**Comment by shsa992** [comment]
> Oh, sorry @agarny about this. I presumed you guys were asleep now. OK so should I revert the use case 4 changes?

Yes please @mahyar-osn

**Comment by agarny** [comment]
I would:
 - update your fork (since my PR for use case 4 has now been merged in);
 - split your PR into two or three, for use cases 1, 3 and 4 (if you added new stuff to use case 4).

**Comment by mahyar-osn** [comment]
OK. Will do it now.

**Comment by shsa992** [comment]
> OK. Will do it now.

Thanks, Mahyar. Much appreciated!

**Pull request merged**
