### PR TITLE
Tidying up Data viewer syntax

### PR DESCRIPTION
**Pull request by nickerso**
based on top of #18

### CODE REVIEW

**Comment by rchristie** [comment]
Note Mahyar has done some commits to fix the other PR which I just merged.

**Comment by rchristie** [comment]
Will probably be easier if you catch up to ABI master. Have you seen this trick:
https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser

**Comment by nickerso** [comment]
updated.

**Comment by rchristie** [comment]
_images/plot_refine_result.png not .jpg. Can you fix this?

**Comment by shsa992** [comment]
> _images/plot_refine_result.png not .jpg. Can you fix this?

I have fixed this .......pushing changes to github

**Comment by nickerso** [comment]
I've also fixed it :)

**Comment by rchristie** [comment]
Does this page show what you want?
https://github.com/nickerso/MAPcore-Documentation/blob/tidy-up-2/source/DataViewer.rst
It has 2 images together... does it make sense?

**Comment by nickerso** [comment]
probably not, but best to get everything updated and in sync so we can have a concerted push to get things finished

**Review by rchristie — APPROVED** [review]

**Pull request merged**
